Import System.Runtime.InteropServices

' In SDK-style projects such as this one, several assembly attributes that were historically
' defined in this file are now automatically added during build and populated with
' values defined in project properties. For details of which attributes are included
' and how to customise this process see: https://aka.ms/assembly-info-properties


' Setting ComVisible to false makes the types in this assembly not visible to COM
' components.  If you need to access a type in this assembly from COM, set the ComVisible
' attribute to true on that type.

<Assembly: ComVisible(False)> 

' The following GUID is for the ID of the typelib if this project is exposed to COM.

<Assembly: Guid("538a1168-39dc-401a-9d67-fdbee36a5613")> 


@rootUrl=https://localhost:7101/api/Company
@Token =eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNDVoMDk4YmI4cmViZXIxYncycjR2NHZiODk0NSIsImp0aSI6ImJmZmU0YzliLTM5OWUtNDJkZi04YzlmLTkwY2YyZThlYjJjMSIsImlhdCI6IjE3MTMyNzMyODkiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiQWRtaW4iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IkFkbWluIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJDb21wYW55SWQiOiIyIiwiVXNlcklkIjoiMSIsIlJvbGVJZCI6IjQiLCJuYmYiOjE3MTMyNzMyODksImV4cCI6MTcxNTg2NTI4OSwiaXNzIjoiSXNzdWVyIiwiYXVkIjoiQXVkaWVuY2UifQ.c25OWD5Ank6d36oBw-0vOB3e5WecdPKJ5aoYpk7AS7U

### Get All
GET {{rootUrl}}/Get
Authorization: Bearer {{Token}}

#####  Get by Id
GET {{rootUrl}}/GetbyId?id=2
Authorization: Bearer {{Token}}

##### Save / Update

POST {{rootUrl}}/SaveUpdate
Authorization: Bearer {{Token}}
Content-Type: application/json

  {      
    "companyCode": "C-003",
    "companyName": "BusinessBay - 3",
    "companyAddress": "Dubai",
    "isActive": true,
    "email": "bay@email.com",
    "contactNumber": "87t8788"
  }

#### Delete
DELETE {{rootUrl}}/Delete?id=4
Authorization: Bearer {{Token}}