Import System.Runtime.InteropServices

' In SDK-style projects such as this one, several assembly attributes that were historically
' defined in this file are now automatically added during build and populated with
' values defined in project properties. For details of which attributes are included
' and how to customise this process see: https://aka.ms/assembly-info-properties


' Setting ComVisible to false makes the types in this assembly not visible to COM
' components.  If you need to access a type in this assembly from COM, set the ComVisible
' attribute to true on that type.

<Assembly: ComVisible(False)> 

' The following GUID is for the ID of the typelib if this project is exposed to COM.

<Assembly: Guid("538a1168-39dc-401a-9d67-fdbee36a5613")> 


@rootUrl=https://localhost:7101/api/Role
@Token =eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNDVoMDk4YmI4cmViZXIxYncycjR2NHZiODk0NSIsImp0aSI6IjBhZTY3OWNjLTdiODMtNGU4NC05OTc4LTk1NTFkMDg5YWM0NyIsImlhdCI6IjE3MTI4NjU3ODgiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiQWRtaW4iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IkFkbWluIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJDb21wYW55SWQiOiIyIiwiVXNlcklkIjoiMSIsIlJvbGVJZCI6IjEiLCJuYmYiOjE3MTI4NjU3ODgsImV4cCI6MTcxNTQ1Nzc4OCwiaXNzIjoiSXNzdWVyIiwiYXVkIjoiQXVkaWVuY2UifQ.EWbBy-MxOcenezQ8XR61C8KMi9J7Zxvn6AA7YmCYLQw
### Get All
GET {{rootUrl}}/Get


#####  Get by Id
GET {{rootUrl}}/GetbyId?id=2

##### Save / Update

POST {{rootUrl}}/SaveUpdate
Content-Type: application/json

  {
      "id" :2,
  "roleName": "User",
  "roleDescription": "User",
  "sequence": 2,
  "isActive": true
  }

#### Delete
DELETE {{rootUrl}}/Delete?id=5